create table patients(
	SSN CHAR(11) NOT NULL PRIMARY KEY,
    P_NAME VARCHAR(30) NOT NULL, 
    ADDRESS VARCHAR(50) NOT NULL,
    AGE INT NOT NULL
);
create table doctors(
	SSN CHAR(11) NOT NULL PRIMARY KEY,
    D_NAME VARCHAR(30) NOT NULL, 
    SPECIALTY VARCHAR(20) NOT NULL,
    EXPERIENCE INT NOT NULL 
);
create table pharma_companies(
	C_NAME VARCHAR(20) NOT NULL PRIMARY KEY,
    PHONE VARCHAR(12) NOT NULL
);
create table pharmacy(
	NAME VARCHAR(20) NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(50) NOT NULL, 
    PHONE VARCHAR(12) NOT NULL
);
create table doctor_patient(
	P_SSN CHAR(11)  NOT NULL REFERENCES PATIENTS(SSN),
    D_SSN CHAR(11) NOT NULL REFERENCES DOCTORS(SSN),
    IS_PRIMARY BOOLEAN DEFAULT FALSE
);
create table drugs(
	TRADENAME VARCHAR(20) NOT NULL,
    PCOMPANY_NAME VARCHAR(20) NOT NULL REFERENCES pharma_companies(C_NAME),
    FORMULA VARCHAR(50) NOT NULL,
    PRIMARY KEY (TRADENAME, PCOMPANY_NAME)
);
create table sold_drugs(
	PHARMA_NAME VARCHAR(20) NOT NULL REFERENCES pharmacy(NAME),
    TRADENAME VARCHAR(20) NOT NULL REFERENCES drugs(TRADENAME),
    PCOMPANY_NAME VARCHAR(20) NOT NULL REFERENCES drugs(PCOMPANY_NAME),
    PRICE INT NOT NULL 
);
create table prescription(
	PID INT NOT NULL PRIMARY KEY SERIAL,
	P_DATE DATE NOT NULL, 
    QUANTITY INT NOT NULL,
    PHARMA_NAME VARCHAR(20) NOT NULL REFERENCES drugs(PCOMPANY_NAME),
    TRADENAME VARCHAR(20) NOT NULL REFERENCES drugs(TRADENAME)
);
create table prescribed_drugs(
	D_SSN CHAR(11) NOT NULL REFERENCES doctors(SSN),
    P_SSN CHAR(11) NOT NULL REFERENCES patients(SSN),
	PID INT REFERENCES prescription(PID)
);